version: "3.8"
services:
  sa_user_postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sa_user
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d sa_user"]
      interval: 3s
      timeout: 2s
      retries: 20
    networks:
      - default

  sa_user:
    image: sa_user:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      sa_user_postgres:
        condition: service_healthy
    environment:
      - DB_HOST=sa_user_postgres
      - DB_PORT=5432

    networks:
      - default
      
networks:
  default:
    driver: bridge
  
