version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sa_user
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d sa_user"]
      interval: 3s
      timeout: 2s
      retries: 20

  sa_user:
    image: sa_user:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    driver: bridge

